version: "2"

services:
  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    hostname: mongo
    ports:
     - "27017-27019:27017-27019"
  backend:
    build: ./exnaton-backend
    image: gregscontainerregistry.azurecr.io/exnaton-backend
    container_name: exnaton-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment: 
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_USER=root
      - MONGO_PASSWORD=rootpassword
      - MONGO_DBNAME=admin
      - EXNATON_BASE_URL=https://dev.exnaton.com/develop/api/v1
      - EXNATON_USER=anonymous+challenge@exnaton.com
      - EXNATON_PASSWORD=exnaton
    restart: 'always'
  frontend:
    build: ./exnaton_frontend
    image: gregscontainerregistry.azurecr.io/exnaton-frontend
    container_name: exnaton-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: 'always'